---
title: "Rap Feature Network - Analysis"
author: "David J. Barney"
date: "1/22/2020"
output: html_document
---

# Setup

# Data Preparation
## Tidy Spotify Data

## Network Format 

## Create edge weights
```{r Lengthen feature lists, eval=FALSE}
tidy_tracks <- read_csv("../1_data/tidy_tracks.csv")

tidy_tracks_long <- tidy_tracks %>%
  mutate(feature = str_split(feature, ",")) %>%
  unchop(feature)

all_tracklists_with_features_unnested <-
  all_tracklists %>%
  unnest(feature, keep_empty = TRUE)

write_csv(tidy_tracks_long, "../1_data/tidy_tracks_long.csv")
```

```{r Pre, eval=FALSE}
## Filter out entities with only 1 occurence
# Count occurences in artists vector
artist_count <- feats %>%
  group_by(artist) %>%
  summarise(artist_count = n()) 

# Count occurences in feature_list vector
feature_list_count <- feats %>%
  group_by(feature) %>%
  summarise(feature_list_count = n())
```

```{r, eval=FALSE}
## Filter out entities with only 1 occurence
# Count occurences in artists vector
artist_count <- feats %>%
  group_by(artist) %>%
  summarise(artist_count = n()) %>%
  rename(entity = artist) %>%
  ungroup()

# Count occurences in feature_list vector
feature_list_count <- feats %>%
  group_by(feature_list) %>%
  summarise(feature_list_count = n()) %>%
  rename(entity = feature_list) %>%
  ungroup()

# Aggregate occurences
entity_counts <- full_join(artist_count, 
                           feature_list_count,
                           by = "entity")

entity_counts <- entity_counts %>%
  rowwise() %>%
  mutate(total_counts = sum(artist_count,feature_list_count, na.rm = TRUE))

entity_counts <- entity_counts %>%
  select(entity, total_counts) %>%
  filter(total_counts >= 2)
```

```{r, eval=FALSE}
# Edge list, filtered
edge_list <- feats %>%
  filter(artist %in% entity_counts$entity | feature_list %in% entity_counts$entity) %>%
  select(artist, feature_list)

edge_list[sample(nrow(edge_list), 5), ]
``` 

```{r Create a nodes list, eval=FALSE}
# Isolate artists and features
artists <- edge_list %>%
  distinct(artist) %>% 
  rename(label = artist)

#artists <- artists[[1]]

features <- edge_list %>%
  distinct(feature_list) %>% 
  rename(label = feature_list)

#features <- features[[1]]

# Aggregate all entities
nodes <- full_join(artists,features) %>%
  rowid_to_column("id")

nodes[sample(nrow(nodes), 5), ]
```

```{r Add frequency weights to the edge list, eval=FALSE}
weighted_edge_list <- edge_list %>%
  group_by(artist,feature_list) %>%
  summarise(weight = n()) %>%
  ungroup()

weighted_edge_list[sample(nrow(weighted_edge_list), 5), ]
```

```{r Merge edge and node lists, eval=FALSE}
edges <- weighted_edge_list %>%
  rename(artist_chr = artist) %>%
  rename(featured_chr = feature_list)

edges <- edges %>% 
  left_join(nodes, by = c("artist_chr" = "label")) %>%
  rename(artist = id)

edges <- edges %>%
  left_join(nodes, by = c("featured_chr" = "label")) %>%
  rename(featured = id) 

edges <- edges %>%
  select(weight, artist, featured)

edges <- edges[c(2,3,1)]
```

# Network Analysis with `igraph`
```{r Create the igraph object, eval=FALSE}
routes_igraph <- graph_from_data_frame(d = edges, vertices = nodes, directed = TRUE)
routes_igraph
```

```{r Print edgelist from igraph object, eval=FALSE}
as_edgelist(routes_igraph, names=T)
```

```{r Print adjacency matrix, eval=FALSE}
as_adjacency_matrix(routes_igraph, attr="weight")
```

## Plot Entire Network Graph
```{r Initial network plot, eval=FALSE}
set.seed(489)
plot(routes_igraph, edge.arrow.size = 0.2, vertex.size = 5,vertex.label = NA)
```

```{r Plot with layout from Davidson-Harel algorithm, eval=FALSE}
set.seed(475)
routes_igraph_simple <- simplify(routes_igraph, remove.multiple = F, remove.loops = T) 
continuous_pal <- viridis(length(unique(degree(routes_igraph_simple))))
vertex_pal_degree <- continuous_pal[as.factor(as.numeric(degree(routes_igraph_simple)))]

l <- layout_with_dh(routes_igraph_simple)

pdf("../3_output/rap_feat_plot.pdf")
plot(routes_igraph_simple, layout = l, 
     edge.arrow.size = 0.2, edge.curved=.1, edge.width = 0.25, 
     vertex.size = degree(routes_igraph_simple)/4, vertex.color = vertex_pal_degree,
     vertex.label = ifelse(degree(routes_igraph_simple) > 10, V(routes_igraph_simple)$label, NA),
     vertex.label.family="Helvetica", vertex.label.cex = 0.5, vertex.label.dist = 1, vertex.label.color="black")
dev.off()
```

## Preliminary Community Detection
```{r  Naive community detection, eval=FALSE}
set.seed(475)

communities <- cluster_walktrap(routes_igraph_simple, weights = E(routes_igraph_simple)$weight, steps = 2,
  merges = TRUE, modularity = TRUE, membership = TRUE)

largest_comms <- which(table(communities$membership) >= 20)
largest_comms <- as.numeric(largest_comms)
# Remove the largest community
largest_comms <- largest_comms[-(which(largest_comms == 2))]

keep_comms <- V(routes_igraph_simple)[communities$membership %in% largest_comms]

routes_igraph_simple_small <- induced_subgraph(routes_igraph_simple, keep_comms)
communities_subset <- cluster_walktrap(routes_igraph_simple_small, weights = E(routes_igraph_simple_small)$weight, steps = 2,
  merges = TRUE, modularity = TRUE, membership = TRUE)

pdf(file="../3_output/rap_feat_plot_w_comms.pdf")
plot(communities_subset, routes_igraph_simple_small, layout = l, 
     edge.arrow.size = 0.2, edge.curved=.1, edge.width = 0.25,
     vertex.size = degree(routes_igraph_simple)/4, vertex.color = vertex_pal_degree,
     vertex.label = ifelse(degree(routes_igraph_simple) > 10, V(routes_igraph_simple)$label, NA),
     vertex.label.family="Helvetica", vertex.label.cex = 0.5, vertex.label.dist = 1, vertex.label.color="black")
dev.off()
```

```{r Show just 1 community, eval=FALSE}
one_comm <- largest_comms[1]

keep_one_comm <- V(routes_igraph_simple)[communities$membership %in% one_comm]

routes_igraph_simple_onecomm <- induced_subgraph(routes_igraph_simple, keep_one_comm)
communities_subset_onecomm <- cluster_walktrap(routes_igraph_simple_onecomm, 
                                               weights = E(routes_igraph_simple_small)$weight, 
                                               steps = 2, merges = TRUE, modularity = TRUE, membership = TRUE)

pdf(file="../3_output/rap_feat_plot_one_comm.pdf")
plot(communities_subset_onecomm, routes_igraph_simple_onecomm, layout = l, 
     edge.arrow.size = 0.2, edge.curved=.1, edge.width = 0.25,
     vertex.size = degree(routes_igraph_simple)/4, vertex.color = vertex_pal_degree,
     vertex.label = ifelse(degree(routes_igraph_simple) > 10, V(routes_igraph_simple)$label, NA),
     vertex.label.family="Helvetica", vertex.label.cex = 0.5, vertex.label.dist = 1, vertex.label.color="black")
dev.off()
```

## Ugly Plots

```{r Create the igraph object, eval=FALSE}
routes_igraph <- graph_from_data_frame(d = edges, vertices = nodes, directed = TRUE)
routes_igraph
```

```{r Plot a nicer looking graph, eval=FALSE}
set.seed(305)
routes_igraph_simple <- simplify(routes_igraph, remove.multiple = F, remove.loops = T) 
plot(routes_igraph_simple, 
     edge.arrow.size = 0.2, edge.curved=.1, edge.width = 0.25,
     vertex.size = 1,
     vertex.label = ifelse(degree(routes_igraph_simple) > 10, V(routes_igraph_simple)$label, NA),
     vertex.label.family="Helvetica", vertex.label.cex = 0.5, vertex.label.dist = 3, vertex.label.color="black") 
```

```{r Plot with layout as random, eval=FALSE}
set.seed(397)
l <- layout.random(routes_igraph_simple)
plot(routes_igraph_simple, layout = l,
     edge.arrow.size = 0.2, edge.curved=.1, edge.width = 0.25,
     vertex.size = 1, 
     vertex.label = ifelse(degree(routes_igraph_simple) > 10, V(routes_igraph_simple)$label, NA),
     vertex.label.family="Helvetica", vertex.label.cex = 0.5, vertex.label.dist = 3, vertex.label.color="black") 
```


```{r Plot with layout from graphopt algorithm, eval=FALSE}
set.seed(264)
l <- layout_with_graphopt(routes_igraph)
plot(routes_igraph_simple, layout = l,
     edge.arrow.size = 0.2, edge.curved=.1, edge.width = 0.25,
     vertex.size = 1, 
     vertex.label = ifelse(degree(routes_igraph_simple) > 10, V(routes_igraph_simple)$label, NA),
     vertex.label.family="Helvetica", vertex.label.cex = 0.5, vertex.label.dist = 3, vertex.label.color="black")
```

```{r Plot with layout from Fruchterman-Reingold algorithm, eval=FALSE}
set.seed(761)
l <- layout_with_fr(routes_igraph)
plot(routes_igraph_simple, layout = l,
     edge.arrow.size = 0.2, edge.curved=.1, edge.width = 0.25,
     vertex.size = 1, 
     vertex.label = ifelse(degree(routes_igraph_simple) > 10, V(routes_igraph_simple)$label, NA),
     vertex.label.family="Helvetica", vertex.label.cex = 0.5, vertex.label.dist = 3, vertex.label.color="black")
```

```{r Plot with layout from mutlidimensional scaling, eval=FALSE}
set.seed(678)
l <- layout_with_mds(routes_igraph)
plot(routes_igraph_simple, layout = l,
     edge.arrow.size = 0.2, edge.curved=.1, edge.width = 0.25,
     vertex.size = 1, 
     vertex.label = ifelse(degree(routes_igraph_simple) > 10, V(routes_igraph_simple)$label, NA),
     vertex.label.family="Helvetica", vertex.label.cex = 0.5, vertex.label.dist = 3, vertex.label.color="black")
```